pool_types:
  - name: "AllyHub Desktop App"
    endpoints:
      - name: "tasks_fetch"
        method: "GET"
        description: "Fetch all tasks"
      - name: "tasks_update"
        method: "POST"
        description: "Update task status"
      - name: "chat_history"
        method: "GET"
        description: "Get chat conversation history"
      - name: "chat_stream"
        method: "POST"
        description: "Stream chat messages"
      - name: "notifications_fetch"
        method: "GET"
        description: "Fetch notifications"
      - name: "notifications_status"
        method: "POST"
        description: "Update notification status"

  - name: "Web API"
    endpoints:
      - name: "auth_login"
        method: "POST"
        description: "User authentication endpoint"
      - name: "auth_logout"
        method: "POST"
        description: "User logout endpoint"
      - name: "data_fetch"
        method: "GET"
        description: "Fetch data from API"
      - name: "data_update"
        method: "PUT"
        description: "Update data via API"

  - name: "Mobile App"
    endpoints:
      - name: "push_notifications"
        method: "POST"
        description: "Send push notifications"
      - name: "user_profile"
        method: "GET"
        description: "Get user profile data"
      - name: "app_config"
        method: "GET"
        description: "Get mobile app configuration"
      - name: "sync_data"
        method: "POST"
        description: "Synchronize mobile data"

  - name: "IoT Device"
    endpoints:
      - name: "device_status"
        method: "GET"
        description: "Get device status"
      - name: "device_control"
        method: "POST"
        description: "Control device actions"
      - name: "sensor_data"
        method: "GET"
        description: "Get sensor readings"
      - name: "device_config"
        method: "PUT"
        description: "Update device configuration"
