pool_types:
  - name: "AllyHub Desktop App v1"
    endpoints:
      - name: "chat_fetch"
        method: "POST"
        description: "Fetch chat conversations"
        documentation: "https://allyhub.com/docs/chat/fetch/conversations"
      - name: "chat_one"
        method: "POST"
        description: "Fetch chat conversation"
        documentation: "https://allyhub.com/docs/chat/fetch/conversation"
      - name: "chat_create"
        method: "POST"
        description: "Create chat conversation"
        documentation: "https://allyhub.com/docs/chat/create"
      - name: "chat_message"
        method: "POST"
        description: "Send chat message"
        documentation: "https://allyhub.com/docs/chat/message"
        
      - name: "task_fetch"
        method: "POST"
        description: "Fetch tasks"
        documentation: "https://allyhub.com/docs/tasks/fetch"
      - name: "task_create"
        method: "POST"
        description: "Create task"
        documentation: "https://allyhub.com/docs/tasks/create"
      - name: "task_update"
        method: "POST"
        description: "Update task"
        documentation: "https://allyhub.com/docs/tasks/update"

      - name: "notification_fetch"
        method: "POST"
        description: "Fetch notifications"
        documentation: "https://allyhub.com/docs/notifications/fetch"
      - name: "notification_update"
        method: "POST"
        description: "Update notification"
        documentation: "https://allyhub.com/docs/notifications/update"

      - name: "action_fetch"
        method: "POST"
        description: "Fetch actions"
        documentation: "https://allyhub.com/docs/actions/fetch"
